runtime: python39

service: backend-service
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker main:app --timeout 120

instance_class: F2

env_variables:
  PINECONE_API_KEY: "${PINECONE_API_KEY}"
  OPENAI_API_KEY: "${OPENAI_API_KEY}"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65 